# Generated by Django 6.0.1 on 2026-01-30 01:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs', max_length=100, unique=True, verbose_name='Slug')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, help_text='Descreva brevemente esta categoria', verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, help_text='Número para ordenar as categorias (menor vem primeiro)', verbose_name='Ordem')),
                ('icone', models.CharField(blank=True, default='bi-tag', help_text='Classe do Bootstrap Icons (ex: bi-tag, bi-box, bi-cup)', max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('codigo', models.CharField(help_text='Código único do produto (ex: ACB-001)', max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('cor', models.CharField(blank=True, help_text='Ex: Transparente, Fumê, Rosa, Azul', max_length=50, verbose_name='Cor')),
                ('dimensoes', models.CharField(blank=True, help_text='Ex: 30x30cm, 25x25x25cm', max_length=100, verbose_name='Dimensões')),
                ('espessura', models.CharField(blank=True, help_text='Ex: 3mm, 5mm, 8mm', max_length=20, verbose_name='Espessura')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de Venda')),
                ('estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/', verbose_name='Foto do Produto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='catalogo_pr_codigo_ea7b19_idx'), models.Index(fields=['categoria', 'ativo'], name='catalogo_pr_categor_ef8659_idx')],
            },
        ),
    ]
